//! ViewScript Launcher
//!
//! Native wrapper that manages WASI binary distribution and execution.
//!
//! ## Architecture
//!
//! ```text
//! ~/.viewscript/
//!   bin/vsc-core.wasm     ← Cached WASI binary
//!   version               ← Current version string
//!   last_check            ← Timestamp of last update check
//! ```
//!
//! ## Responsibilities
//!
//! A. Auto-update: Check remote version once per hour, download if newer
//! B. Fallback: Extract embedded WASI binary on first run
//! C. Execute: Run WASI binary via wasmtime with CLI args

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use std::time::{Duration, SystemTime};

use wasmtime::{Engine, Linker, Module, Store};
use wasmtime_wasi::preview1::{self, WasiP1Ctx};
use wasmtime_wasi::{DirPerms, FilePerms, WasiCtxBuilder};

/// Embedded WASI binary (zstd compressed)
/// Generated by: cargo build -p vsc-cli --target wasm32-wasip1 --release
///               zstd -19 target/wasm32-wasip1/release/vsc.wasm -o embedded/vsc-core.wasm.zst
const EMBEDDED_WASM_ZST: &[u8] = include_bytes!("../embedded/vsc-core.wasm.zst");

/// Embedded version string
const EMBEDDED_VERSION: &str = env!("CARGO_PKG_VERSION");

/// Update check interval (1 hour)
const UPDATE_CHECK_INTERVAL: Duration = Duration::from_secs(3600);

/// Remote release URL base
const RELEASE_BASE_URL: &str = "https://viewscript.pages.dev/releases";

fn main() -> ExitCode {
    let vs_home = match dirs::home_dir() {
        Some(home) => home.join(".viewscript"),
        None => {
            eprintln!("Error: Could not determine home directory");
            return ExitCode::FAILURE;
        }
    };

    // Ensure directories exist
    if let Err(e) = fs::create_dir_all(vs_home.join("bin")) {
        eprintln!("Error creating ~/.viewscript/bin: {}", e);
        return ExitCode::FAILURE;
    }

    // A: Update check (synchronous, but only once per hour)
    if should_check_update(&vs_home) {
        if let Some(remote_version) = check_remote_version() {
            let local_version = read_local_version(&vs_home);
            if local_version.as_deref() != Some(remote_version.as_str()) {
                if download_and_extract(&vs_home).is_ok() {
                    write_local_version(&vs_home, &remote_version);
                }
            }
        }
        update_last_check(&vs_home);
    }

    // B: Fallback - extract embedded binary if not present
    let wasm_path = vs_home.join("bin/vsc-core.wasm");
    if !wasm_path.exists() {
        match extract_embedded(&wasm_path) {
            Ok(()) => {
                // Record embedded version
                let _ = fs::write(vs_home.join("version"), EMBEDDED_VERSION);
            }
            Err(e) => {
                eprintln!("Error extracting embedded WASI binary: {}", e);
                return ExitCode::FAILURE;
            }
        }
    }

    // C: Execute via wasmtime
    let args: Vec<String> = std::env::args().skip(1).collect();
    run_wasi(&wasm_path, &args)
}

/// Check if we should perform an update check (1 hour since last check)
fn should_check_update(vs_home: &Path) -> bool {
    let last_check_path = vs_home.join("last_check");

    match fs::metadata(&last_check_path) {
        Ok(meta) => {
            if let Ok(modified) = meta.modified() {
                if let Ok(elapsed) = SystemTime::now().duration_since(modified) {
                    return elapsed > UPDATE_CHECK_INTERVAL;
                }
            }
            true // If we can't determine, check anyway
        }
        Err(_) => true, // File doesn't exist, should check
    }
}

/// Update the last_check timestamp
fn update_last_check(vs_home: &Path) {
    let last_check_path = vs_home.join("last_check");
    // Touch the file
    if let Ok(mut f) = fs::File::create(&last_check_path) {
        let _ = f.write_all(b"");
    }
}

/// Check the remote version
fn check_remote_version() -> Option<String> {
    let url = format!("{}/version/latest", RELEASE_BASE_URL);

    let response = reqwest::blocking::Client::new()
        .get(&url)
        .timeout(Duration::from_secs(5))
        .send()
        .ok()?;

    if response.status().is_success() {
        Some(response.text().ok()?.trim().to_string())
    } else {
        None
    }
}

/// Read local version from ~/.viewscript/version
fn read_local_version(vs_home: &Path) -> Option<String> {
    fs::read_to_string(vs_home.join("version"))
        .ok()
        .map(|s| s.trim().to_string())
}

/// Write local version to ~/.viewscript/version
fn write_local_version(vs_home: &Path, version: &str) {
    let _ = fs::write(vs_home.join("version"), version);
}

/// Download and extract the WASI binary from remote
fn download_and_extract(vs_home: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let url = format!("{}/bin/vsc-core.wasm.zst", RELEASE_BASE_URL);

    let response = reqwest::blocking::Client::new()
        .get(&url)
        .timeout(Duration::from_secs(60))
        .send()?;

    if !response.status().is_success() {
        return Err(format!("HTTP {}", response.status()).into());
    }

    let compressed = response.bytes()?;
    let decompressed = zstd::decode_all(&compressed[..])?;

    let wasm_path = vs_home.join("bin/vsc-core.wasm");
    fs::write(&wasm_path, decompressed)?;

    Ok(())
}

/// Extract the embedded WASI binary
fn extract_embedded(wasm_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let decompressed = zstd::decode_all(EMBEDDED_WASM_ZST)?;
    fs::write(wasm_path, decompressed)?;
    Ok(())
}

/// Execute the WASI binary via wasmtime (WASIp1/preview1)
fn run_wasi(wasm_path: &Path, args: &[String]) -> ExitCode {
    let engine = Engine::default();

    let module = match Module::from_file(&engine, wasm_path) {
        Ok(m) => m,
        Err(e) => {
            eprintln!("Error loading WASI module: {}", e);
            return ExitCode::FAILURE;
        }
    };

    let mut linker: Linker<WasiP1Ctx> = Linker::new(&engine);
    if let Err(e) = preview1::add_to_linker_sync(&mut linker, |ctx| ctx) {
        eprintln!("Error setting up WASI linker: {}", e);
        return ExitCode::FAILURE;
    }

    // Build WASI context with stdio, env, args, and filesystem access
    let mut wasi_builder = WasiCtxBuilder::new();
    wasi_builder.inherit_stdio();
    wasi_builder.inherit_env();

    // Add "vsc" as argv[0], then the actual args
    let mut full_args: Vec<String> = vec!["vsc".to_string()];
    full_args.extend(args.iter().cloned());
    wasi_builder.args(&full_args);

    // Mount current directory for filesystem access
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    if let Err(e) = wasi_builder.preopened_dir(&cwd, ".", DirPerms::all(), FilePerms::all()) {
        eprintln!("Error mounting current directory: {}", e);
        return ExitCode::FAILURE;
    }

    let wasi_ctx = wasi_builder.build_p1();
    let mut store = Store::new(&engine, wasi_ctx);

    let instance = match linker.instantiate(&mut store, &module) {
        Ok(i) => i,
        Err(e) => {
            eprintln!("Error instantiating WASI module: {}", e);
            return ExitCode::FAILURE;
        }
    };

    let start_func = match instance.get_typed_func::<(), ()>(&mut store, "_start") {
        Ok(f) => f,
        Err(e) => {
            eprintln!("Error getting _start function: {}", e);
            return ExitCode::FAILURE;
        }
    };

    match start_func.call(&mut store, ()) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            // Check if it's a normal exit with code
            if let Some(exit) = e.downcast_ref::<wasmtime_wasi::I32Exit>() {
                ExitCode::from(exit.0 as u8)
            } else {
                eprintln!("WASI execution error: {}", e);
                ExitCode::FAILURE
            }
        }
    }
}
// ViewScript CLI v0.1.0
