//! Gröbner Basis Computation using Buchberger's Algorithm
//!
//! A Gröbner basis is a particular generating set of a polynomial ideal
//! with desirable computational properties. It allows:
//!
//! - **Ideal membership testing**: Check if a polynomial is in an ideal
//! - **Solving polynomial systems**: Via variable elimination
//! - **Polynomial reduction**: Canonical remainders
//!
//! ## Algorithm
//!
//! Buchberger's algorithm computes a Gröbner basis by:
//! 1. Start with the input polynomials as the initial basis
//! 2. For each pair of polynomials, compute their S-polynomial
//! 3. Reduce the S-polynomial by the current basis
//! 4. If the remainder is non-zero, add it to the basis
//! 5. Repeat until no new polynomials are added
//!
//! ## Complexity Warning
//!
//! Gröbner basis computation has worst-case doubly exponential complexity
//! (EXPSPACE-complete). The hierarchical solver pipeline (L0 -> L1 -> L2)
//! ensures this is only invoked when necessary.

use super::monomial::{Monomial, MonomialOrder};
use super::polynomial::Polynomial;
use crate::Rational;
use std::collections::HashSet;

/// Configuration for Gröbner basis computation.
#[derive(Clone, Debug)]
pub struct GroebnerConfig {
    /// The monomial ordering to use.
    pub order: MonomialOrder,
    /// Maximum number of iterations before giving up.
    pub max_iterations: usize,
    /// Whether to reduce the final basis (remove redundant polynomials).
    pub reduce_basis: bool,
}

impl Default for GroebnerConfig {
    fn default() -> Self {
        Self {
            order: MonomialOrder::Lexicographic,
            max_iterations: 10000,
            reduce_basis: true,
        }
    }
}

/// Result of Gröbner basis computation.
#[derive(Clone, Debug)]
pub struct GroebnerResult {
    /// The computed Gröbner basis.
    pub basis: Vec<Polynomial>,
    /// Number of S-polynomials computed.
    pub s_polynomials_computed: usize,
    /// Number of non-zero reductions.
    pub reductions_added: usize,
    /// Whether computation completed (vs. hit iteration limit).
    pub completed: bool,
}

/// Compute the S-polynomial of two polynomials.
///
/// The S-polynomial is designed to cancel the leading terms:
///   S(f, g) = (lcm(LM(f), LM(g)) / LT(f)) * f - (lcm(LM(f), LM(g)) / LT(g)) * g
///
/// This is the key operation in Buchberger's algorithm.
pub fn s_polynomial(f: &Polynomial, g: &Polynomial, order: MonomialOrder) -> Polynomial {
    let (lc_f, lm_f) = match f.leading_term(order) {
        Some(lt) => lt,
        None => return Polynomial::zero(),
    };
    let (lc_g, lm_g) = match g.leading_term(order) {
        Some(lt) => lt,
        None => return Polynomial::zero(),
    };

    // Compute lcm of leading monomials
    let lcm = lm_f.lcm(&lm_g);

    // Compute multipliers
    let mult_f = lcm.divide(&lm_f).unwrap();
    let mult_g = lcm.divide(&lm_g).unwrap();

    // S(f, g) = (lcm/LT(f)) * f - (lcm/LT(g)) * g
    // We need to scale to cancel leading coefficients too
    let scaled_f = f.mul_monomial(&mult_f).scale(&lc_g);
    let scaled_g = g.mul_monomial(&mult_g).scale(&lc_f);

    scaled_f.sub(&scaled_g)
}

/// Compute a Gröbner basis for the ideal generated by the input polynomials.
///
/// Uses Buchberger's algorithm with the specified configuration.
pub fn compute_groebner_basis(
    polynomials: &[Polynomial],
    config: &GroebnerConfig,
) -> GroebnerResult {
    let mut basis: Vec<Polynomial> = polynomials
        .iter()
        .filter(|p| !p.is_zero())
        .map(|p| p.make_monic(config.order))
        .collect();

    if basis.is_empty() {
        return GroebnerResult {
            basis: vec![],
            s_polynomials_computed: 0,
            reductions_added: 0,
            completed: true,
        };
    }

    // Track which pairs we've processed
    let mut processed_pairs: HashSet<(usize, usize)> = HashSet::new();
    let mut s_polys_computed = 0;
    let mut reductions_added = 0;
    let mut iterations = 0;

    loop {
        iterations += 1;
        if iterations > config.max_iterations {
            return GroebnerResult {
                basis,
                s_polynomials_computed: s_polys_computed,
                reductions_added,
                completed: false,
            };
        }

        let mut new_poly = None;

        // Find a pair that hasn't been processed
        'outer: for i in 0..basis.len() {
            for j in (i + 1)..basis.len() {
                if processed_pairs.contains(&(i, j)) {
                    continue;
                }
                processed_pairs.insert((i, j));

                // Compute S-polynomial
                let s = s_polynomial(&basis[i], &basis[j], config.order);
                s_polys_computed += 1;

                if s.is_zero() {
                    continue;
                }

                // Reduce by current basis
                let remainder = s.reduce(&basis, config.order);

                if !remainder.is_zero() {
                    new_poly = Some(remainder.make_monic(config.order));
                    break 'outer;
                }
            }
        }

        match new_poly {
            Some(p) => {
                basis.push(p);
                reductions_added += 1;
            }
            None => {
                // No new polynomials found, we're done
                break;
            }
        }
    }

    // Optionally reduce the basis
    if config.reduce_basis {
        basis = reduce_groebner_basis(basis, config.order);
    }

    GroebnerResult {
        basis,
        s_polynomials_computed: s_polys_computed,
        reductions_added,
        completed: true,
    }
}

/// Reduce a Gröbner basis to a minimal form.
///
/// Removes polynomials whose leading monomial is divisible by another's,
/// and inter-reduces the remaining polynomials.
fn reduce_groebner_basis(basis: Vec<Polynomial>, order: MonomialOrder) -> Vec<Polynomial> {
    // Step 1: Remove polynomials with divisible leading monomials
    let mut minimal = Vec::new();
    for i in 0..basis.len() {
        let lm_i = match basis[i].leading_monomial(order) {
            Some(m) => m,
            None => continue,
        };

        let mut is_minimal = true;
        for j in 0..basis.len() {
            if i == j {
                continue;
            }
            if let Some(lm_j) = basis[j].leading_monomial(order) {
                if lm_i.is_divisible_by(&lm_j) && lm_i != lm_j {
                    is_minimal = false;
                    break;
                }
            }
        }

        if is_minimal {
            minimal.push(basis[i].clone());
        }
    }

    // Step 2: Inter-reduce
    let mut reduced = Vec::new();
    for i in 0..minimal.len() {
        let others: Vec<_> = minimal
            .iter()
            .enumerate()
            .filter(|(j, _)| *j != i)
            .map(|(_, p)| p.clone())
            .collect();

        let r = minimal[i].reduce(&others, order);
        if !r.is_zero() {
            reduced.push(r.make_monic(order));
        }
    }

    reduced
}

/// Solve a polynomial system using Gröbner basis and back-substitution.
///
/// For systems with finitely many solutions, the Gröbner basis in
/// lexicographic order has a special "triangular" form that allows
/// back-substitution.
///
/// Returns a list of solutions, where each solution is a map from
/// variable index to value.
#[derive(Clone, Debug)]
pub struct PolynomialSolution {
    /// Map from variable index to its value.
    pub values: std::collections::BTreeMap<u32, Rational>,
    /// Whether this is a real solution (all values are real).
    /// Note: Since we use rationals, all our solutions are real.
    pub is_real: bool,
}

/// Result of solving a polynomial system.
#[derive(Clone, Debug)]
pub enum SolveResult {
    /// The system has no solutions.
    NoSolution,
    /// The system has a finite number of solutions.
    FiniteSolutions(Vec<PolynomialSolution>),
    /// The system has infinitely many solutions (underdetermined).
    InfiniteSolutions,
    /// The solver could not determine the solutions (e.g., complex roots).
    Undetermined { reason: String },
}

/// Attempt to solve a polynomial system.
///
/// This uses Gröbner basis computation followed by back-substitution.
/// Currently limited to systems that reduce to univariate polynomials
/// with rational roots.
pub fn solve_polynomial_system(polynomials: &[Polynomial]) -> SolveResult {
    if polynomials.is_empty() {
        return SolveResult::InfiniteSolutions;
    }

    // Compute Gröbner basis in lex order for elimination
    let config = GroebnerConfig {
        order: MonomialOrder::Lexicographic,
        max_iterations: 10000,
        reduce_basis: true,
    };

    let result = compute_groebner_basis(polynomials, &config);

    if !result.completed {
        return SolveResult::Undetermined {
            reason: "Gröbner basis computation did not complete".to_string(),
        };
    }

    if result.basis.is_empty() {
        return SolveResult::InfiniteSolutions;
    }

    // Check for inconsistency (basis contains a non-zero constant)
    for p in &result.basis {
        if p.total_degree() == 0 && !p.is_zero() {
            return SolveResult::NoSolution;
        }
    }

    // Try to extract solutions via back-substitution
    // For this, we need the basis to have a triangular structure
    extract_solutions_from_basis(&result.basis, config.order)
}

/// Extract solutions from a Gröbner basis in lex order.
///
/// In lex order, the basis often has a triangular structure:
/// - One polynomial in just x_n (the last variable in lex order)
/// - One polynomial in x_{n-1} and x_n
/// - etc.
///
/// We solve from the last variable back to the first.
fn extract_solutions_from_basis(basis: &[Polynomial], _order: MonomialOrder) -> SolveResult {
    // Find all variables in the system
    let mut all_vars: Vec<u32> = basis.iter().flat_map(|p| p.variables()).collect();
    all_vars.sort();
    all_vars.dedup();

    if all_vars.is_empty() {
        return SolveResult::InfiniteSolutions;
    }

    // Start with empty partial solutions
    let mut solutions: Vec<std::collections::BTreeMap<u32, Rational>> =
        vec![std::collections::BTreeMap::new()];

    // Process variables in reverse order (last variable first in lex)
    // In lex order with variables [0, 1, 2], the Gröbner basis will have
    // polynomials where variable 2 appears alone, then 1 with 2, then 0 with others
    for &var in all_vars.iter().rev() {
        let mut new_solutions = Vec::new();

        for partial in &solutions {
            // Try each polynomial in the basis
            for poly in basis {
                // Substitute known values
                let substituted = substitute_partial(poly, partial);

                if substituted.is_zero() {
                    // This polynomial is satisfied, continue with current partial solution
                    continue;
                }

                // Check if this polynomial now only involves our target variable
                let remaining_vars = substituted.variables();
                if remaining_vars.len() == 1 && remaining_vars[0] == var {
                    // Univariate in var - solve it
                    if let Some(roots) = solve_univariate(&substituted, var) {
                        for root in roots {
                            let mut sol = partial.clone();
                            sol.insert(var, root);
                            // Only add if not already present
                            if !new_solutions.iter().any(|s| *s == sol) {
                                new_solutions.push(sol);
                            }
                        }
                    }
                }
            }

            // If we didn't find any univariate polynomial for this variable,
            // keep the partial solution (variable might be free)
            if new_solutions.is_empty() || !new_solutions.iter().any(|s| s.contains_key(&var)) {
                // Try to find if there's a linear relation we can solve
                for poly in basis {
                    let substituted = substitute_partial(poly, partial);
                    if substituted.is_zero() {
                        continue;
                    }

                    // Check if var appears with degree 1 and we can isolate it
                    if substituted.variables().contains(&var) && substituted.total_degree() == 1 {
                        if let Some(roots) = solve_univariate(&substituted, var) {
                            for root in roots {
                                let mut sol = partial.clone();
                                sol.insert(var, root);
                                if !new_solutions.iter().any(|s| *s == sol) {
                                    new_solutions.push(sol);
                                }
                            }
                        }
                    }
                }
            }
        }

        if !new_solutions.is_empty() {
            solutions = new_solutions;
        }
        // If new_solutions is empty, keep the current partial solutions
        // (the variable might not be constrained or might be free)
    }

    if solutions.is_empty() {
        return SolveResult::NoSolution;
    }

    // Verify solutions against all original polynomials
    let verified: Vec<_> = solutions
        .into_iter()
        .filter(|sol| verify_solution(basis, sol))
        .map(|values| PolynomialSolution {
            values,
            is_real: true,
        })
        .collect();

    if verified.is_empty() {
        SolveResult::NoSolution
    } else {
        SolveResult::FiniteSolutions(verified)
    }
}

/// Substitute partial solution values into a polynomial.
fn substitute_partial(
    poly: &Polynomial,
    values: &std::collections::BTreeMap<u32, Rational>,
) -> Polynomial {
    let mut result = Polynomial::zero();

    for (coeff, monomial) in poly.iter_terms() {
        let mut new_coeff = coeff.clone();
        let mut remaining_vars = Vec::new();

        for var in monomial.variables() {
            let exp = monomial.exponent(var);
            if let Some(val) = values.get(&var) {
                // Substitute: multiply coeff by val^exp
                for _ in 0..exp {
                    new_coeff = new_coeff * val.clone();
                }
            } else {
                remaining_vars.push((var, exp));
            }
        }

        let new_mon = Monomial::from_exponents(remaining_vars);
        result = result.add(&Polynomial::term(new_coeff, new_mon));
    }

    result
}

/// Solve a univariate polynomial for rational roots.
///
/// Uses the Rational Root Theorem: if p/q is a root, then p divides
/// the constant term and q divides the leading coefficient.
fn solve_univariate(poly: &Polynomial, var: u32) -> Option<Vec<Rational>> {
    // Check that poly is actually univariate in var
    let vars = poly.variables();
    if vars.len() > 1 || (vars.len() == 1 && vars[0] != var) {
        return None;
    }

    if poly.is_zero() {
        // Any value is a solution - return a default
        return Some(vec![Rational::zero()]);
    }

    // Get coefficients as a polynomial in var
    let degree = poly.total_degree();
    if degree == 0 {
        // Constant polynomial - no solutions (or already checked to be zero)
        return Some(vec![]);
    }

    // For linear polynomial ax + b = 0, solution is x = -b/a
    if degree == 1 {
        let mut a = Rational::zero();
        let mut b = Rational::zero();

        for (coeff, mon) in poly.iter_terms() {
            if mon.is_constant() {
                b = coeff.clone();
            } else {
                a = coeff.clone();
            }
        }

        if a == Rational::zero() {
            return Some(vec![]);
        }

        return Some(vec![Rational::zero() - b / a]);
    }

    // For quadratic ax² + bx + c = 0, use quadratic formula
    // But we need to handle irrational roots - for now, only find rational roots
    if degree == 2 {
        let mut a = Rational::zero();
        let mut b = Rational::zero();
        let mut c = Rational::zero();

        for (coeff, mon) in poly.iter_terms() {
            match mon.exponent(var) {
                0 => c = coeff.clone(),
                1 => b = coeff.clone(),
                2 => a = coeff.clone(),
                _ => {}
            }
        }

        // Discriminant = b² - 4ac
        let disc = b.clone() * b.clone() - Rational::from_int(4) * a.clone() * c.clone();

        // Check if discriminant is a perfect square (rational)
        // This is a simplified check - in practice we'd need more sophisticated
        // rational root finding
        if disc == Rational::zero() {
            // One repeated root: -b/(2a)
            let root = (Rational::zero() - b) / (Rational::from_int(2) * a);
            return Some(vec![root]);
        }

        // For now, try rational roots using the rational root theorem
        return find_rational_roots(poly, var);
    }

    // For higher degree, use rational root theorem
    find_rational_roots(poly, var)
}

/// Find rational roots using the Rational Root Theorem.
fn find_rational_roots(poly: &Polynomial, var: u32) -> Option<Vec<Rational>> {
    // Get constant term and leading coefficient
    let mut constant = Rational::zero();
    let mut leading = Rational::zero();
    let degree = poly.total_degree();

    for (coeff, mon) in poly.iter_terms() {
        if mon.is_constant() {
            constant = coeff.clone();
        }
        if mon.exponent(var) == degree {
            leading = coeff.clone();
        }
    }

    if leading == Rational::zero() {
        return None;
    }

    // If constant is zero, then 0 is a root
    let mut roots = Vec::new();
    if constant == Rational::zero() {
        roots.push(Rational::zero());
    }

    // For simplicity, try small integer candidates
    // A full implementation would factor the constant and leading coefficient
    let candidates: Vec<i64> = vec![
        1, -1, 2, -2, 3, -3, 4, -4, 5, -5, 6, -6, 10, -10,
    ];

    for p in &candidates {
        for q in &[1i64, 2, 3, 4, 5, 6, 10] {
            let candidate = Rational::new(*p, *q);
            let mut values = std::collections::BTreeMap::new();
            values.insert(var, candidate.clone());
            let result = poly.evaluate(&values);
            if result == Rational::zero() {
                if !roots.iter().any(|r| *r == candidate) {
                    roots.push(candidate);
                }
            }
        }
    }

    Some(roots)
}

/// Verify that a solution satisfies all polynomials in the system.
fn verify_solution(
    polynomials: &[Polynomial],
    solution: &std::collections::BTreeMap<u32, Rational>,
) -> bool {
    for poly in polynomials {
        let result = poly.evaluate(solution);
        if result != Rational::zero() {
            return false;
        }
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_s_polynomial() {
        // f = x² - y, g = xy - 1
        // S(f, g) should reduce nicely
        let x = Polynomial::var(0);
        let y = Polynomial::var(1);
        let one = Polynomial::constant(Rational::from_int(1));

        let f = x.mul(&x).sub(&y);
        let g = x.mul(&y).sub(&one);

        let s = s_polynomial(&f, &g, MonomialOrder::Lexicographic);
        assert!(!s.is_zero());
    }

    #[test]
    fn test_groebner_simple() {
        // System: x + y = 2, x - y = 0
        // Solution: x = 1, y = 1
        let x = Polynomial::var(0);
        let y = Polynomial::var(1);
        let two = Polynomial::constant(Rational::from_int(2));

        let p1 = x.add(&y).sub(&two);  // x + y - 2
        let p2 = x.sub(&y);             // x - y

        let config = GroebnerConfig::default();
        let result = compute_groebner_basis(&[p1, p2], &config);

        assert!(result.completed);
        assert!(!result.basis.is_empty());
    }

    #[test]
    fn test_solve_linear_system() {
        // System: x + y = 3, x - y = 1
        // Solution: x = 2, y = 1
        let x = Polynomial::var(0);
        let y = Polynomial::var(1);
        let three = Polynomial::constant(Rational::from_int(3));
        let one = Polynomial::constant(Rational::from_int(1));

        let p1 = x.add(&y).sub(&three);  // x + y - 3
        let p2 = x.sub(&y).sub(&one);    // x - y - 1

        // First compute Gröbner basis to debug
        let config = GroebnerConfig::default();
        let gb_result = compute_groebner_basis(&[p1.clone(), p2.clone()], &config);

        // The Gröbner basis should reduce to triangular form
        // For this system, it should be something like: y - 1, x - 2

        let result = solve_polynomial_system(&[p1, p2]);

        match result {
            SolveResult::FiniteSolutions(solutions) => {
                assert!(!solutions.is_empty(), "Should have at least one solution");
                let sol = &solutions[0].values;
                // Check both variables are solved
                assert!(sol.contains_key(&0) || sol.contains_key(&1),
                    "Should solve at least one variable. Basis: {:?}", gb_result.basis);
                if sol.contains_key(&0) {
                    assert_eq!(sol.get(&0), Some(&Rational::from_int(2)));
                }
                if sol.contains_key(&1) {
                    assert_eq!(sol.get(&1), Some(&Rational::from_int(1)));
                }
            }
            SolveResult::NoSolution => {
                panic!("Got NoSolution. Basis: {:?}", gb_result.basis);
            }
            other => panic!("Expected FiniteSolutions, got {:?}. Basis: {:?}", other, gb_result.basis),
        }
    }

    #[test]
    fn test_solve_quadratic_system() {
        // System: x² = 4
        // Solutions: x = 2, x = -2
        let x = Polynomial::var(0);
        let four = Polynomial::constant(Rational::from_int(4));

        let p = x.mul(&x).sub(&four);  // x² - 4

        let result = solve_polynomial_system(&[p]);

        match result {
            SolveResult::FiniteSolutions(solutions) => {
                assert_eq!(solutions.len(), 2);
                let vals: Vec<_> = solutions.iter().map(|s| s.values.get(&0).unwrap().clone()).collect();
                assert!(vals.contains(&Rational::from_int(2)));
                assert!(vals.contains(&Rational::from_int(-2)));
            }
            other => panic!("Expected FiniteSolutions, got {:?}", other),
        }
    }

    #[test]
    fn test_no_solution() {
        // System: x = 1, x = 2 (inconsistent)
        let x = Polynomial::var(0);
        let one = Polynomial::constant(Rational::from_int(1));
        let two = Polynomial::constant(Rational::from_int(2));

        let p1 = x.sub(&one);  // x - 1
        let p2 = x.sub(&two);  // x - 2

        let result = solve_polynomial_system(&[p1, p2]);

        match result {
            SolveResult::NoSolution => {}
            other => panic!("Expected NoSolution, got {:?}", other),
        }
    }
}
