//! FFI Manifest Bridge for vs-web Target
//!
//! This module defines the schema for FFI manifests generated by the Vite plugin.
//! The manifest describes:
//! - `bindings`: Q-dimension variables bound to JS functions (evaluated every frame)
//! - `triggers`: Conditions that fire FFI calls on rising edge
//!
//! This is vs-web target specific and NOT part of vsc-core.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use vsc_core::types::ConditionKind;

// =============================================================================
// FFI Manifest Schema
// =============================================================================

/// FFI manifest generated by Vite plugin at build time.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FfiManifest {
    /// Schema version for forward compatibility.
    #[serde(default = "default_version")]
    pub version: u32,

    /// Entity name → EntityId mapping (resolved at build time).
    #[serde(default)]
    pub entity_map: HashMap<String, u64>,

    /// Q-dimension bindings (evaluated every frame).
    #[serde(default)]
    pub bindings: Vec<FfiBinding>,

    /// Trigger conditions (evaluated post-solve, fire on rising edge).
    #[serde(default)]
    pub triggers: Vec<FfiTrigger>,
}

fn default_version() -> u32 {
    1
}

/// A Q-dimension binding that maps a JS function to a Q variable.
///
/// The JS function is evaluated every frame, and its result is injected
/// into the QSnapshot under `bind_name`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FfiBinding {
    /// Unique identifier for this binding.
    pub ffi_id: u64,

    /// Name of the Q variable (used in QSnapshot).
    pub bind_name: String,

    /// JS module path (relative to project root).
    pub module_path: String,

    /// Exported function name from the module.
    pub export_name: String,
}

/// A trigger condition that fires an FFI call on rising edge.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FfiTrigger {
    /// Unique identifier for this trigger (used as ConditionId).
    pub trigger_id: u64,

    /// FFI function to call when triggered.
    pub ffi_id: u64,

    /// The condition to evaluate post-solve.
    pub condition: ConditionKind,

    /// Arguments to pass to the FFI function (static or derived).
    #[serde(default)]
    pub args: Vec<FfiArg>,
}

/// Argument specification for FFI calls.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum FfiArg {
    /// Static value (JSON literal).
    Static { value: serde_json::Value },

    /// Reference to a Q variable value.
    QRef { name: String },

    /// Reference to an entity's resolved coordinate.
    EntityCoord {
        entity_id: u64,
        component: String, // "x", "y", "value"
    },
}

// =============================================================================
// FFI Call Request (returned from tick)
// =============================================================================

/// A pending FFI call to be dispatched by JS runtime.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PendingFfiCall {
    /// The FFI function ID to call.
    pub ffi_id: u64,

    /// Resolved arguments for the call.
    pub args: Vec<serde_json::Value>,
}

/// Result of a tick operation, containing pending FFI calls.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TickResult {
    /// FFI calls triggered this frame (empty if none).
    pub pending_ffi_calls: Vec<PendingFfiCall>,
}

impl TickResult {
    /// Create an empty tick result (no FFI calls).
    pub fn empty() -> Self {
        Self {
            pending_ffi_calls: Vec::new(),
        }
    }

    /// Create a tick result with pending FFI calls.
    pub fn with_calls(calls: Vec<PendingFfiCall>) -> Self {
        Self {
            pending_ffi_calls: calls,
        }
    }

    /// Serialize to JSON string for wasm_bindgen return.
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string(self)
    }
}

// =============================================================================
// T2: FfiManifest Deserialization Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// T2.1: Valid manifest with all fields deserializes correctly
    #[test]
    fn test_deserialize_valid_manifest() {
        let json = r#"{
            "version": 1,
            "entity_map": { "button": 42, "cursor": 57 },
            "bindings": [
                {
                    "ffi_id": 1,
                    "bind_name": "mouse.x",
                    "module_path": "./input.ts",
                    "export_name": "getMouseX"
                }
            ],
            "triggers": [
                {
                    "trigger_id": 100,
                    "ffi_id": 2,
                    "condition": { "kind": "bounds_overlap", "entity_a": 42, "entity_b": 57 },
                    "args": []
                }
            ]
        }"#;

        let manifest: FfiManifest = serde_json::from_str(json).unwrap();

        assert_eq!(manifest.version, 1);
        assert_eq!(manifest.entity_map.get("button"), Some(&42));
        assert_eq!(manifest.bindings.len(), 1);
        assert_eq!(manifest.bindings[0].bind_name, "mouse.x");
        assert_eq!(manifest.triggers.len(), 1);
        assert_eq!(manifest.triggers[0].trigger_id, 100);
    }

    /// T2.2: Manifest with missing optional fields uses defaults
    #[test]
    fn test_deserialize_minimal_manifest() {
        let json = r#"{}"#;

        let manifest: FfiManifest = serde_json::from_str(json).unwrap();

        assert_eq!(manifest.version, 1); // Default
        assert!(manifest.entity_map.is_empty());
        assert!(manifest.bindings.is_empty());
        assert!(manifest.triggers.is_empty());
    }

    /// T2.3: Reject invalid ConditionKind
    #[test]
    fn test_deserialize_invalid_condition_kind() {
        let json = r#"{
            "triggers": [
                {
                    "trigger_id": 100,
                    "ffi_id": 2,
                    "condition": { "kind": "unknown_condition", "foo": "bar" }
                }
            ]
        }"#;

        let result: Result<FfiManifest, _> = serde_json::from_str(json);
        assert!(result.is_err(), "Should reject unknown condition kind");
    }

    /// T2.4: Reject trigger missing required fields
    #[test]
    fn test_deserialize_trigger_missing_ffi_id() {
        let json = r#"{
            "triggers": [
                {
                    "trigger_id": 100,
                    "condition": { "kind": "bounds_overlap", "entity_a": 1, "entity_b": 2 }
                }
            ]
        }"#;

        let result: Result<FfiManifest, _> = serde_json::from_str(json);
        assert!(result.is_err(), "Should reject trigger without ffi_id");
    }

    /// T2.5: FfiArg variants deserialize correctly
    #[test]
    fn test_deserialize_ffi_args() {
        let json = r#"{
            "triggers": [
                {
                    "trigger_id": 100,
                    "ffi_id": 2,
                    "condition": { "kind": "bounds_overlap", "entity_a": 1, "entity_b": 2 },
                    "args": [
                        { "type": "static", "value": 42 },
                        { "type": "q_ref", "name": "input.x" },
                        { "type": "entity_coord", "entity_id": 10, "component": "x" }
                    ]
                }
            ]
        }"#;

        let manifest: FfiManifest = serde_json::from_str(json).unwrap();
        let args = &manifest.triggers[0].args;

        assert_eq!(args.len(), 3);

        match &args[0] {
            FfiArg::Static { value } => assert_eq!(value, &serde_json::json!(42)),
            _ => panic!("Expected Static arg"),
        }

        match &args[1] {
            FfiArg::QRef { name } => assert_eq!(name, "input.x"),
            _ => panic!("Expected QRef arg"),
        }

        match &args[2] {
            FfiArg::EntityCoord {
                entity_id,
                component,
            } => {
                assert_eq!(*entity_id, 10);
                assert_eq!(component, "x");
            }
            _ => panic!("Expected EntityCoord arg"),
        }
    }

    /// T2.6: TickResult serializes correctly
    #[test]
    fn test_tick_result_serialization() {
        let result = TickResult::with_calls(vec![PendingFfiCall {
            ffi_id: 42,
            args: vec![serde_json::json!(100), serde_json::json!("hello")],
        }]);

        let json = result.to_json().unwrap();
        assert!(json.contains("\"ffi_id\":42"));
        assert!(json.contains("\"pending_ffi_calls\""));
    }

    /// T2.7: Empty TickResult serializes to expected format
    #[test]
    fn test_tick_result_empty_serialization() {
        let result = TickResult::empty();
        let json = result.to_json().unwrap();

        assert_eq!(json, r#"{"pending_ffi_calls":[]}"#);
    }
}
