/**
 * ViewScript Constraint Engine C API
 *
 * This header provides C bindings for the ViewScript constraint solver.
 * The engine is headless (no GPU) - rendering is the host's responsibility.
 *
 * ## Quick Start
 *
 * ```c
 * VscEngine* engine = vsc_engine_create();
 *
 * const char* snapshot = "{"values":{}}";
 * int result = vsc_engine_tick(engine, snapshot, strlen(snapshot));
 * if (result != 0) {
 *     // Handle error
 * }
 *
 * char buf[4096];
 * int len = vsc_engine_get_scene_json(engine, buf, sizeof(buf));
 * if (len > 0) {
 *     // buf contains the scene graph as JSON
 *     printf("Scene: %s\n", buf);
 * }
 *
 * vsc_engine_destroy(engine);
 * ```
 *
 * ## Error Codes
 *
 * -  0: Success
 * - -1: Null pointer error
 * - -2: UTF-8 decoding error
 * - -3: JSON parsing error
 * - -4: Solver/internal error
 * - < -100: Buffer too small (|code| - 100 = required size)
 */


#ifndef VIEWSCRIPT_H
#define VIEWSCRIPT_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a ViewScript engine instance.
 *
 * This struct is not repr(C) because it is only passed as an opaque pointer.
 * The C API only sees `*mut VscEngine` and never accesses fields directly.
 */
typedef struct VscEngine VscEngine;

/**
 * Create a new ViewScript engine instance.
 *
 * # Returns
 *
 * A pointer to a new engine instance. The caller is responsible for
 * calling `vsc_engine_destroy()` to free the memory.
 *
 * # Safety
 *
 * The returned pointer is valid until `vsc_engine_destroy()` is called.
 */
struct VscEngine *vsc_engine_create(void);

/**
 * Process a single tick with the given QSnapshot JSON.
 *
 * # Arguments
 *
 * * `engine` - Pointer to the engine instance
 * * `snapshot_json` - Pointer to the JSON string (does not need to be null-terminated)
 * * `snapshot_len` - Length of the JSON string in bytes
 *
 * # Returns
 *
 * - `0`: Success
 * - `-1`: Null pointer (engine or snapshot_json is null)
 * - `-2`: Invalid UTF-8 in snapshot_json
 * - `-3`: JSON parsing error
 * - `-4`: Solver error
 *
 * # Safety
 *
 * * `engine` must be a valid pointer returned by `vsc_engine_create()`
 * * `snapshot_json` must point to valid memory of at least `snapshot_len` bytes
 */
int32_t vsc_engine_tick(struct VscEngine *engine,
                        const char *snapshot_json,
                        uintptr_t snapshot_len);

/**
 * Get the scene graph from the last tick as JSON.
 *
 * # Arguments
 *
 * * `engine` - Pointer to the engine instance
 * * `out_buf` - Buffer to write the JSON string into
 * * `buf_len` - Size of the buffer in bytes
 *
 * # Returns
 *
 * - Positive value: Number of bytes written (excluding null terminator)
 * - `-1`: Null pointer
 * - Negative value < -100: Buffer too small; absolute value minus 100 is the required size
 *
 * # Safety
 *
 * * `engine` must be a valid pointer returned by `vsc_engine_create()`
 * * `out_buf` must point to valid writable memory of at least `buf_len` bytes
 */
int32_t vsc_engine_get_scene_json(struct VscEngine *engine, char *out_buf, uintptr_t buf_len);

/**
 * Add a component to the engine.
 *
 * # Arguments
 *
 * * `engine` - Pointer to the engine instance
 * * `component_type` - Null-terminated C string for component type (e.g., "Rectangle")
 * * `params_json` - Pointer to JSON parameters (does not need to be null-terminated)
 * * `params_len` - Length of the JSON parameters in bytes
 *
 * # Returns
 *
 * - Positive value: EntityId of the created component
 * - `-1`: Null pointer
 * - `-2`: Invalid UTF-8
 * - `-3`: JSON parsing error
 * - `-4`: Invalid component type
 *
 * # Safety
 *
 * * `engine` must be a valid pointer returned by `vsc_engine_create()`
 * * `component_type` must be a valid null-terminated C string
 * * `params_json` must point to valid memory of at least `params_len` bytes
 */
int64_t vsc_engine_add_component(struct VscEngine *engine,
                                 const char *component_type,
                                 const char *params_json,
                                 uintptr_t params_len);

/**
 * Register a Q-variable with the engine.
 *
 * # Arguments
 *
 * * `engine` - Pointer to the engine instance
 * * `q_var_json` - Pointer to JSON QVariable (does not need to be null-terminated)
 * * `q_var_len` - Length of the JSON in bytes
 *
 * # Returns
 *
 * - `0`: Success
 * - `-1`: Null pointer
 * - `-2`: Invalid UTF-8
 * - `-3`: JSON parsing error
 *
 * # Safety
 *
 * * `engine` must be a valid pointer returned by `vsc_engine_create()`
 * * `q_var_json` must point to valid memory of at least `q_var_len` bytes
 */
int32_t vsc_engine_register_q_variable(struct VscEngine *engine,
                                       const char *q_var_json,
                                       uintptr_t q_var_len);

/**
 * Free a ViewScript engine instance.
 *
 * # Arguments
 *
 * * `engine` - Pointer to the engine instance (may be null)
 *
 * # Safety
 *
 * * If `engine` is non-null, it must be a valid pointer returned by `vsc_engine_create()`
 * * After calling this function, the pointer is invalid and must not be used
 */
void vsc_engine_destroy(struct VscEngine *engine);

#endif  /* VIEWSCRIPT_H */
